import math

#math function to demostrate
x = 10
y = math.sqrt(x) 
print( "Square root of ", x ,"is", y)
y1 = math.tan(x)
print("Tan of ", x,"is",y1)
y2 = math.cos(x)
print("Cos of ",x,"is",y2)
y3 = math.sin(x)
print("Sin of ",x,"is",y3)
y4 = math.factorial(x)
print("Factorial of ",x,"is",y4)
y5 = math.log(x)
print("Log of ",x,"is",y5)
y6 = math.isnan(x) 
print("value of",x,"is",y6)
y7 = math.isqrt(x)
print("Value of")
y8 = math.atan(x)
print("Arc tangent of ",x,"is",y8)
y9 = math.acosh(x)
print('Inverse hyperbolic cosine of ',x,"is",y9)
y10 = math.sinh(x)
print("Hyperbolic sine of ",x,"is",y10)
y11 = math.exp(x)
print("Exponential of ",x,"is",y11)
y12 = math.isfinite(x)
import math

#math function to demostrate
x = 10
y = math.sqrt(x) 
print( "Square root of ", x ,"is", y)
y1 = math.tan(x)
print("Tan of ", x,"is",y1)
y2 = math.cos(x)
print("Cos of ",x,"is",y2)
y3 = math.sin(x)
print("Sin of ",x,"is",y3)
y4 = math.factorial(x)
print("Factorial of ",x,"is",y4)
y5 = math.log(x)
print("Log of ",x,"is",y5)
y6 = math.isnan(x)
print("value of",x,"is",y6)
y7 = math.isqrt(x)
print("Value of")
y8 = math.atan(x)
print("Arc tangent of ",x,"is",y8)
y9 = math.acosh(x)
print('Inverse hyperbolic cosine of ',x,"is",y9)
y10 = math.sinh(x)
print("Hyperbolic sine of ",x,"is",y10)
y11 = math.exp(x)
print("Exponential of ",x,"is",y11)
y12 = math.isfinite(x)